sudo: false
language: ruby
bundler_args: --without development
rvm:
  - 2.1.5

before_install:
  - rvm get stable
  - rvm rubygems current
  - gem --version
  - rvm list known
  - travis_retry gem install brakeman

before_script:
  - cp config/database-travis.yml config/database.yml
  - cp config/secrets-travis.yml config/secrets.yml
  - mkdir -p tmp/backup
  - bundle exec rake db:setup

after_script:
  - bundle exec brakeman --format html --output brakeman.html --confidence-level 2
